language: node_js
dist: xenial
node_js:
  - node
  - lts/*
  - '8'
before_install:
  - npm run setup
install:
  - npm install -g codecov
before_script:
  - npm run build
script:
  - npm test
  - npm run lint
  - npm pack
  - npm run pluginInstall